baseurl: /CIS1051-python
repository: tur-learning/CIS1051-python

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: CIS1051 - Python
description: Introduction to Problem solving and Programming in Python.
show_downloads: true